use_frameworks!

platform :ios, '10.0'

target 'MKMThreeProbe_Example' do
  pod 'MKMThreeProbe', :path => '../'

  target 'MKMThreeProbe_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
